version: '3.7'
services:
  crm_lead_validator:
    image: davidgalvis1995/crm_lead_validator:v7
    container_name: crmleadvalidatorcontainer
    ports:
      - 7000:7000
    links:
      - external_service
      - mongodb_container
    depends_on:
      - mongodb_container
      - external_service
    networks:
      - shared-net

  external_service:
    image: davidgalvis1995/externalleadvalidator:latest
    container_name: externalservicecontainer
    ports:
      - 8000:8000
    networks:
      - shared-net

  mongodb_container:
    container_name: mongodbcontainer
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - shared-net

  crm_validator_client:
    image: davidgalvis1995/crm-validator-client
    ports:
      - 3000:80
    restart: always
    depends_on:
      - mongodb_container
      - external_service
      - crm_lead_validator
    networks:
      - shared-net

volumes:
  mongodb_data_container:

networks:
  shared-net:
    driver: bridge